_target_: ripepp.benchmarks.scared.SCARED_Benchmark
_partial_: true
transforms:
  _target_: ripepp.data.data_transforms.Compose
  transforms:
    - _target_: ripepp.data.data_transforms.Normalize
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
    - _target_: ripepp.data.data_transforms.DivisibleBy
      antialias: true
      edge_divisible_by: 1
dry_run: false
seed: 42
min_overlap: 0.4
num_pairs: 200